---
title: "TP_booststrap"
author: "Arthur"
date: "30 septembre 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exercice 1
Cet exercice sert de rappel. 
```{r}
MC.simus <- function(theta, n,Nsim)
{ sortie =rep(NA, Nsim)
  for (nsim in 1:Nsim)
       {  x=rbinom(n, 1, theta)
          sortie[nsim]=mean(x)
        }
return(sortie)
}

n=100
Nsim=1000
theta=0.5
theta.chap=MC.simus(theta,n, Nsim)

par(mfrow=c(1,2))
hist(theta.chap,prob=1)
xx= seq(0,1,by=0.01)
lines(xx, dnorm(xx, theta, sqrt(theta*(1-theta)/n)), col=2)

plot(density(theta.chap))
xx= seq(0,1,by=0.01)
lines(xx, dnorm(xx, theta, sqrt(theta*(1-theta)/n)), col=2)
```

# Exercice 2

### Question 1 

Ici, on travail sur un jeu de données commun à toute la classe. On calcul de manière intuitive $\hat{\theta} = \frac{1}{n}\sum^{n}_{k=1}x_{i}$ .
D'ou le code suivant.
```{r}
n=100
theta=0.5
set.seed(1)        #fixe l'aléa : vous aurez tous le même jeu de données
x=rbinom(n,1,theta)
theta.chap= mean(x)
```

### Question 2

```{r}
xstar = sample(x,n,replace=TRUE)
mean.bootstrap <- function(x, B)
{ ech_boot_mean =rep(NA,B)
  n=length(x)
  for (b in 1:B)
  { xstar=sample(x,n,replace=TRUE)
    ech_boot_mean[b]=mean(xstar)} 
  return(ech_boot_mean)
}
ech_boot_mean=mean.bootstrap(x, B=1000)
```

### Q.2c)
```{r}
library(boot)
moyenne <- function(x,i) {return(mean(x[i]))}
bootsample_mean=boot(x,moyenne,R=1000)
names(bootsample_mean)
```


### Q.3a)
```{r}
par(mfrow=c(1,2))
hist(bootsample_mean$t)
plot(density(bootsample_mean$t))
```

### Q.3b)


### Q.3c)
```{r}
plot(density(sqrt(n)*(bootsample_mean$t-mean(x))))
xx= seq(-2,2,by=0.01)
lines(xx, dnorm(xx,0,sqrt(theta*(1-theta))), col=2)
```

### Q.4)
```{r}
quantile(bootsample_mean$t, c(0.025,0.975)) 
 
ICboot_perc<-boot.ci( bootsample_mean,conf=0.95,type="perc")
ICboot_perc
 
ICboot_bca <-boot.ci(bootsample_mean,conf=0.95,type="bca")
ICboot_bca
```

### D'apres TCL :
```{r}
Binf=mean(x)-1.96*sd(x)/sqrt(n)
Bsup=mean(x)+1.96*sd(x)/sqrt(n)
Binf
Bsup
```

# Exerice 3 

### Question 1
```{r}
 n = 100
 set.seed(1)
 x = rcauchy(n,location = 1)
 true.mediane = 1
```

### Question 2
```{r}
library(boot)
bootsample_median=boot(x,function(x,i) {return(median(x[i]))},R=1000)
par(mfrow=c(1,2))
hist(bootsample_median$t)
plot(density(bootsample_median$t))
```




